### PR TITLE
Add tests from JSONTestSuite

### LINKED ISSUE #47: Adopt tests from "parsing json is a minefield" article
The article in question is http://seriot.ch/parsing_json.php

Here's a test suite of ~300 tests: https://github.com/nst/JSONTestSuite

It'd be good to grab tests from there. We should mark those that currently fail as "todo" so that JSON::Fast remains installable until they are fixed.

### PR DESCRIPTION
**Pull request by Kaiepi**
Fixes #47

### CODE REVIEW

**Comment by timo** [comment]
One of the new lines apparently makes github (and git itself) believe that the test file is binary now; perhaps you can find out which it is and use some escaping to make it plain-old text again?

Also i'd appreciate a comment in the arrays that tells where the tests from this source start, and maybe also a link to the original.

Other than that, good work, thanks!

**Comment by Kaiepi** [comment]
The tests that were making the file appear to be binary were the ones that used unescaped UTF16 and U+FFFF. I removed those, so now it's back to being a text file.

I'll update the pullreq once Rakudo finishes building and I get a chance to test again

**Comment by timo** [comment]
Sorry about the nitpicking, but could you split replacing << >> with « » into a separate commit so that they show up "properly" as different changes in a "git blame"?

**Comment by Kaiepi** [comment]
Sure

**Comment by timo** [comment]
fantastic, thanks!

**Pull request merged**
